accum_days – time_manager
accum_days Function
11 statements
Source File
public pure function accum_days(year, month, day, calendar) result(res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: year
integer, intent(in) :: month
integer, intent(in) :: day
integer, intent(in) :: calendar
Return Value integer
Calls
Called by
Contents
Source Code
accum_days
Source Code
  pure integer function accum_days(year, month, day, calendar) result(res)
    integer, intent(in) :: year
    integer, intent(in) :: month
    integer, intent(in) :: day
    integer, intent(in) :: calendar
    integer mon
    res = day
    do mon = 1, month - 1
      res = res + days_of_month(year, mon, calendar)
    end do
  end function accum_days
Call graph
accum_days calls days_of_month
days_of_month calls is_leap_year
create_datetime_1 calls accum_days
datetime calls create_datetime_1
ceiling_day calls datetime
create_clock calls datetime
ceiling_month calls datetime
timestamp calls datetime
clock calls create_clock