ceiling_month – time_manager
ceiling_month Function
6 statements
Source File
private pure function ceiling_month(this) result(res)
Arguments
Type Intent Optional Attributes Name
class(datetime), intent(in) :: this
Return Value type(datetime)
Calls
Contents
Source Code
ceiling_month
Source Code
  pure type(datetime) function ceiling_month(this) result(res)
    class(datetime), intent(in) :: this
    res = datetime(this%year, this%month, 1, 0, 0, 0, calendar=this%calendar)
    call res%add_months(1)
    return
  end function ceiling_month
Call graph
ceiling_month calls datetime
datetime calls create_datetime_1, create_datetime_2
create_datetime_1 calls accum_days, days_of_month
accum_days calls days_of_month
days_of_month calls is_leap_year