ceiling_day – time_manager
ceiling_day Function
6 statements
Source File
private pure function ceiling_day(this) result(res)
Arguments
Type Intent Optional Attributes Name
class(datetime), intent(in) :: this
Return Value type(datetime)
Calls
Contents
Source Code
ceiling_day
Source Code
  pure type(datetime) function ceiling_day(this) result(res)
    class(datetime), intent(in) :: this
    res = datetime(this%year, this%month, this%day, 0, 0, 0, calendar=this%calendar)
    call res%add_days(1)
    return
  end function ceiling_day
Call graph
ceiling_day calls datetime
datetime calls create_datetime_1, create_datetime_2
create_datetime_1 calls days_of_month, accum_days
days_of_month calls is_leap_year
accum_days calls days_of_month