create_timedelta – time_manager
create_timedelta Function
57 statements
Source File
private pure function create_timedelta(days, hours, minutes, seconds, milliseconds) result(res)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), optional :: days
class(*), intent(in), optional :: hours
class(*), intent(in), optional :: minutes
class(*), intent(in), optional :: seconds
class(*), intent(in), optional :: milliseconds
Return Value type(timedelta)
Called by
Contents
Source Code
create_timedelta
Source Code
  pure type(timedelta) function create_timedelta(days, hours, minutes, seconds, milliseconds) result(res)
    class(*), intent(in), optional :: days
    class(*), intent(in), optional :: hours
    class(*), intent(in), optional :: minutes
    class(*), intent(in), optional :: seconds
    class(*), intent(in), optional :: milliseconds
    if (present(days)) then
      select type (days)
      type is (integer)
        res%days = days
      type is (real(4))
        res%days = days
      type is (real(8))
        res%days = days
      end select
    end if
    if (present(hours)) then
      select type (hours)
      type is (integer)
        res%hours = hours
      type is (real(4))
        res%hours = hours
      type is (real(8))
        res%hours = hours
      end select
    end if
    if (present(minutes)) then
      select type (minutes)
      type is (integer)
        res%minutes = minutes
      type is (real(4))
        res%minutes = minutes
      type is (real(8))
        res%minutes = minutes
      end select
    end if
    if (present(seconds)) then
      select type (seconds)
      type is (integer)
        res%seconds = seconds
      type is (real(4))
        res%seconds = seconds
      type is (real(8))
        res%seconds = seconds
      end select
    end if
    if (present(milliseconds)) then
      select type (milliseconds)
      type is (integer)
        res%milliseconds = milliseconds
      type is (real(4))
        res%milliseconds = milliseconds
      type is (real(8))
        res%milliseconds = milliseconds
      end select
    end if
  end function create_timedelta
Call graph
timedelta calls create_timedelta
sub_datetime calls create_timedelta, sub_datetime
create_clock calls timedelta
timedelta_plus_timedelta calls timedelta
clock calls create_clock