create_datetime_1 – time_manager
create_datetime_1 Function
89 statements
Source File
private pure function create_datetime_1(year, month, day, hour, minute, second, millisecond, julday, days, hours, minutes, seconds, timestamp, timezone, calendar) result(res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: year
integer, intent(in), optional :: month
integer, intent(in), optional :: day
integer, intent(in), optional :: hour
integer, intent(in), optional :: minute
integer, intent(in), optional :: second
integer, intent(in), optional :: millisecond
integer, intent(in), optional :: julday
integer, intent(in), optional :: days
integer, intent(in), optional :: hours
integer, intent(in), optional :: minutes
integer, intent(in), optional :: seconds
class(*), intent(in), optional :: timestamp
class(*), intent(in), optional :: timezone
integer, intent(in), optional :: calendar
Return Value type(datetime)
Calls
Called by
Contents
Source Code
create_datetime_1
Source Code
  pure type(datetime) function create_datetime_1( &
      year,  month,  day,  hour,  minute,  second, millisecond, &
             julday, days, hours, minutes, seconds, &
      timestamp, &
      timezone, calendar) result(res)
    integer, intent(in), optional :: year
    integer, intent(in), optional :: month
    integer, intent(in), optional :: day
    integer, intent(in), optional :: hour
    integer, intent(in), optional :: minute
    integer, intent(in), optional :: second
    integer, intent(in), optional :: millisecond
    integer, intent(in), optional :: julday
    integer, intent(in), optional :: days
    integer, intent(in), optional :: hours
    integer, intent(in), optional :: minutes
    integer, intent(in), optional :: seconds
    class(*), intent(in), optional :: timestamp
    class(*), intent(in), optional :: timezone
    integer, intent(in), optional :: calendar
    real(8) residue_seconds
    integer mon
    if (present(calendar)) res%calendar = calendar
    if (present(timestamp)) then
      ! Assume the start date time is UTC 0001-01-01 00:00:00 defined default_year, default_units
      res%year   = default_year
      res%month  = 1
      res%day    = 1
      res%hour   = 0
      res%minute = 0
      res%second = 0
      res%millisecond = 0
      select type (timestamp)
      type is (integer)
        residue_seconds = timestamp
      type is (real(4))
        residue_seconds = timestamp
      type is (real(8))
        residue_seconds = timestamp
      end select
      call res%add_days(int(residue_seconds / 86400.0))
      residue_seconds = mod(residue_seconds, 86400.0)
      call res%add_hours(int(residue_seconds / 3600.0))
      residue_seconds = mod(residue_seconds, 3600.0)
      call res%add_minutes(int(residue_seconds / 60.0))
      residue_seconds = mod(residue_seconds, 60.0)
      call res%add_seconds(int(residue_seconds))
      call res%add_milliseconds((residue_seconds - int(residue_seconds)) * 1000)
    else
      if (present(year)) res%year = year
      if (present(julday)) then
        res%day = 0
        do mon = 1, 12
          res%day = res%day + days_of_month(year, mon, res%calendar)
          if (res%day > julday) exit
        end do
        res%month = min(mon, 12)
        res%day = julday - accum_days(year, res%month, 0, res%calendar)
      else
        if (present(month)) res%month = month
        if (present(day  )) res%day   = day
      end if
      if (present(hour       )) res%hour        = hour
      if (present(minute     )) res%minute      = minute
      if (present(second     )) res%second      = second
      if (present(millisecond)) res%millisecond = millisecond
      if (present(days       )) call res%add_days(days)
      if (present(hours      )) call res%add_hours(hours)
      if (present(minutes    )) call res%add_minutes(minutes)
      if (present(seconds    )) call res%add_seconds(seconds)
      if (res%second == 60) then
        call res%add_minutes(1)
        res%second = 0
      end if
      if (res%minute == 60) then
        call res%add_hours(1)
        res%minute = 0
      end if
      if (res%hour == 24) then
        call res%add_days(1)
        res%hour = 0
      end if
    end if
    if (present(timezone)) then
      select type (timezone)
      type is (integer)
        res%timezone = timezone
      type is (real(4))
        res%timezone = timezone
      type is (real(8))
        res%timezone = timezone
      end select
    end if
  end function create_datetime_1
Call graph
create_datetime_1 calls days_of_month, accum_days
days_of_month calls is_leap_year
accum_days calls days_of_month
datetime calls create_datetime_1
ceiling_day calls datetime
ceiling_month calls datetime
create_clock calls datetime
timestamp calls datetime
clock calls create_clock