create_clock – time_manager
create_clock Function
17 statements
Source File
private pure function create_clock(d0, d1, dt) result(res)
Arguments
Type Intent Optional Attributes Name
class(datetime), intent(in) :: d0
class(datetime), intent(in) :: d1
class(timedelta), intent(in) :: dt
Return Value type(clock)
Calls
Called by
Contents
Source Code
create_clock
Source Code
  pure type(clock) function create_clock(d0, d1, dt) result(res)
    class(datetime), intent(in) :: d0, d1
    class(timedelta),intent(in) :: dt
    if (d1 > d0) then
        res%strtTime = d0
        res%Time     = d0
        res%lastTime = d1
        res%dt       = dt
    else
        res%strtTime = datetime(1980, 1, 1, 0, 0, 0)
        res%Time     = datetime(1980, 1, 1, 0, 0, 0)
        res%lastTime = datetime(1981, 1, 1, 0, 0, 0)
        res%dt       = timedelta(hours=24)
    end if
    res%index_d = 0
    res%index_m = 0
  end function create_clock
Call graph
create_clock calls datetime, timedelta
datetime calls create_datetime_1, create_datetime_2
timedelta calls create_timedelta
create_datetime_1 calls days_of_month, accum_days
days_of_month calls is_leap_year
accum_days calls days_of_month
clock calls create_clock