days_of_month – time_manager
days_of_month Function
11 statements
Source File
public pure function days_of_month(year, month, calendar) result(res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: year
integer, intent(in) :: month
integer, intent(in) :: calendar
Return Value integer
Calls
Called by
Contents
Source Code
days_of_month
Source Code
  pure integer function days_of_month(year, month, calendar) result(res)
    integer, intent(in) :: year
    integer, intent(in) :: month
    integer, intent(in) :: calendar
    integer, parameter :: days(12) = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    if (month == 2 .and. is_leap_year(year) .and. calendar == gregorian) then
      res = 29
    else
      res = days(month)
    end if
  end function days_of_month
Call graph
days_of_month calls is_leap_year
add_days calls days_of_month
accum_days calls days_of_month
create_datetime_1 calls days_of_month, accum_days
days_in_year calls days_of_month
sub_datetime calls days_of_month, sub_datetime
datetime calls create_datetime_1
ceiling_day calls datetime
ceiling_month calls datetime
create_clock calls datetime
timestamp calls datetime
clock calls create_clock