is_leap_year – time_manager
is_leap_year Function
4 statements
Source File
public pure function is_leap_year(year) result(res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: year
Return Value logical
Called by
Contents
Source Code
is_leap_year
Source Code
  pure logical function is_leap_year(year) result(res)
    integer, intent(in) :: year
    res = (mod(year, 4) == 0 .and. .not. mod(year, 100) == 0) .or. (mod(year, 400) == 0)
  end function is_leap_year
Call graph
days_of_year calls is_leap_year
sub_datetime calls is_leap_year, sub_datetime, days_of_month
days_of_month calls is_leap_year
days_in_year calls days_of_month
accum_days calls days_of_month
create_datetime_1 calls days_of_month, accum_days
add_days calls days_of_month
datetime calls create_datetime_1
ceiling_day calls datetime
ceiling_month calls datetime
create_clock calls datetime
timestamp calls datetime
clock calls create_clock