timestamp – time_manager
timestamp Function
18 statements
Source File
private function timestamp(this, timezone)
Arguments
Type Intent Optional Attributes Name
class(datetime), intent(in) :: this
class(*), intent(in), optional :: timezone
Return Value real(kind=8)
Calls
Contents
Source Code
timestamp
Source Code
  function timestamp(this, timezone)
    class(datetime), intent(in) :: this
    class(*), intent(in), optional :: timezone
    real(8) timestamp
    type(timedelta) dt
    dt = this - datetime(default_year)
    timestamp = dt%total_days()
    if (present(timezone)) then
      select type (timezone)
      type is (integer)
        timestamp = timestamp - (this%timezone - timezone)/24.d0
      type is (real(4))
        timestamp = timestamp - (this%timezone - timezone)/24.d0
      type is (real(8))
        timestamp = timestamp - (this%timezone - timezone)/24.d0
      end select
    end if
  end function timestamp
Call graph
timestamp calls datetime
datetime calls create_datetime_1, create_datetime_2
create_datetime_1 calls days_of_month, accum_days
days_of_month calls is_leap_year
accum_days calls days_of_month