clock – time_manager
clock Interface
3 statements
Source File
public interface clock
initial function set to the same name with type
Calls
Contents
Module Procedures
create_clock
Module Procedures
private pure function create_clock(d0, d1, dt) result(res)
Arguments
Type Intent Optional Attributes Name
class(datetime), intent(in) :: d0
class(datetime), intent(in) :: d1
class(timedelta), intent(in) :: dt
Return Value type(clock)
Call graph
clock calls create_clock
create_clock calls datetime, timedelta
datetime calls create_datetime_1, create_datetime_2
timedelta calls create_timedelta
create_datetime_1 calls days_of_month, accum_days
days_of_month calls is_leap_year
accum_days calls days_of_month