datetime – time_manager
datetime Interface
4 statements
Source File
public interface datetime
initial function set to the same name with type
Calls
Called by
Contents
Module Procedures
create_datetime_1 create_datetime_2
Module Procedures
private pure function create_datetime_1(year, month, day, hour, minute, second, millisecond, julday, days, hours, minutes, seconds, timestamp, timezone, calendar) result(res)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: year
integer, intent(in), optional :: month
integer, intent(in), optional :: day
integer, intent(in), optional :: hour
integer, intent(in), optional :: minute
integer, intent(in), optional :: second
integer, intent(in), optional :: millisecond
integer, intent(in), optional :: julday
integer, intent(in), optional :: days
integer, intent(in), optional :: hours
integer, intent(in), optional :: minutes
integer, intent(in), optional :: seconds
class(*), intent(in), optional :: timestamp
class(*), intent(in), optional :: timezone
integer, intent(in), optional :: calendar
Return Value type(datetime)
private function create_datetime_2(datetime_str, format_str, timezone, calendar) result(res)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: datetime_str
character(len=*), intent(in), optional :: format_str
class(*), intent(in), optional :: timezone
integer, intent(in), optional :: calendar
Return Value type(datetime)
Call graph
datetime calls create_datetime_1, create_datetime_2
create_datetime_1 calls accum_days, days_of_month
accum_days calls days_of_month
days_of_month calls is_leap_year
ceiling_day calls datetime
create_clock calls datetime
ceiling_month calls datetime
timestamp calls datetime
clock calls create_clock