timedelta – time_manager
timedelta Interface
3 statements
Source File
public interface timedelta
initial function set to the same name with type
Calls
Called by
Contents
Module Procedures
create_timedelta
Module Procedures
private pure function create_timedelta(days, hours, minutes, seconds, milliseconds) result(res)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), optional :: days
class(*), intent(in), optional :: hours
class(*), intent(in), optional :: minutes
class(*), intent(in), optional :: seconds
class(*), intent(in), optional :: milliseconds
Return Value type(timedelta)
Call graph
timedelta calls create_timedelta
create_clock calls timedelta
timedelta_plus_timedelta calls timedelta
clock calls create_clock